In [1]:
import pandas as pd

In [4]:
dt = pd.read_csv("few_shot_examples.csv")
dt.head(8)

                                              SMILES  Label
0  [H+].C2=C1C(OC(=NC1=CC=C2Cl)NCC)(C3=CC=CC=C3)C...    1.0
1  CN[C@H]1[C@@H](O)[C@H]2O[C@@H](O[C@@H]3[C@@H](...    0.0
2            C1=CC=CC2=C1C(C3=C(N(C)C2=O)C=CC=C3)OCC    1.0
3  CC1(C)S[C@@H]2C(NC(=O)[C@H](NC(=O)C3=CNc4cccnc...    0.0
4  [C@H]2(N(C1=CC=C(C(=C1)Cl)Cl)C(CC)=O)[C@@H](CC...    1.0
5  CC1(C)SC2C(N([C@H](C(=O)NC(=O)CN)c3ccccc3)C(=N...    0.0
6   C1=C(N=C2[N]1C(=C(CC)C(=N2)OC)C)C(C3=CC=CC=C3)=O    1.0
7  CC(C)CC(OC(=O)c1occc1)C(=O)N[C@H]2[C@H]3SC(C)(...    0.0

In [5]:
dt

                                              SMILES  Label
0  [H+].C2=C1C(OC(=NC1=CC=C2Cl)NCC)(C3=CC=CC=C3)C...    1.0
1  CN[C@H]1[C@@H](O)[C@H]2O[C@@H](O[C@@H]3[C@@H](...    0.0
2            C1=CC=CC2=C1C(C3=C(N(C)C2=O)C=CC=C3)OCC    1.0
3  CC1(C)S[C@@H]2C(NC(=O)[C@H](NC(=O)C3=CNc4cccnc...    0.0
4  [C@H]2(N(C1=CC=C(C(=C1)Cl)Cl)C(CC)=O)[C@@H](CC...    1.0
5  CC1(C)SC2C(N([C@H](C(=O)NC(=O)CN)c3ccccc3)C(=N...    0.0
6   C1=C(N=C2[N]1C(=C(CC)C(=N2)OC)C)C(C3=CC=CC=C3)=O    1.0
7  CC(C)CC(OC(=O)c1occc1)C(=O)N[C@H]2[C@H]3SC(C)(...    0.0